apiVersion: v1
kind: Service
metadata:
  name: corvimae-dot-com-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: corvimae-dot-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corvimae-dot-com
  labels:
    app: corvimae-dot-com
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corvimae-dot-com
  template:
    metadata:
      labels:
        app: corvimae-dot-com
    spec:
      containers:
      - name: corvimae-dot-com
        image: corvimae/corvimae-dot-com:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 102m
          requests:
            cpu: 102m